//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSeriesWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://at.gov.pt/", ConfigurationName="ServiceSeriesWS.SeriesWS")]
    public interface SeriesWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://at.gov.pt/SeriesWS/registarSerieRequest", ReplyAction="http://at.gov.pt/SeriesWS/registarSerieResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceSeriesWS.registarSerieResponse> registarSerieAsync(ServiceSeriesWS.registarSerieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://at.gov.pt/SeriesWS/finalizarSerieRequest", ReplyAction="http://at.gov.pt/SeriesWS/finalizarSerieResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceSeriesWS.finalizarSerieResponse> finalizarSerieAsync(ServiceSeriesWS.finalizarSerieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://at.gov.pt/SeriesWS/consultarSeriesRequest", ReplyAction="http://at.gov.pt/SeriesWS/consultarSeriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceSeriesWS.consultarSeriesResponse> consultarSeriesAsync(ServiceSeriesWS.consultarSeriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://at.gov.pt/SeriesWS/anularSerieRequest", ReplyAction="http://at.gov.pt/SeriesWS/anularSerieResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceSeriesWS.anularSerieResponse> anularSerieAsync(ServiceSeriesWS.anularSerieRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class seriesResp : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private seriesInfo infoSerieField;
        
        private operationResultInfo infoResultOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public seriesInfo infoSerie
        {
            get
            {
                return this.infoSerieField;
            }
            set
            {
                this.infoSerieField = value;
                this.RaisePropertyChanged("infoSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public operationResultInfo infoResultOper
        {
            get
            {
                return this.infoResultOperField;
            }
            set
            {
                this.infoResultOperField = value;
                this.RaisePropertyChanged("infoResultOper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class seriesInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string serieField;
        
        private string tipoSerieField;
        
        private string classeDocField;
        
        private string tipoDocField;
        
        private string numInicialSeqField;
        
        private string numFinalSeqField;
        
        private System.DateTime dataInicioPrevUtilizField;
        
        private string seqUltimoDocEmitidoField;
        
        private string meioProcessamentoField;
        
        private string numCertSWFaturField;
        
        private string codValidacaoSerieField;
        
        private System.DateTime dataRegistoField;
        
        private string estadoField;
        
        private string motivoEstadoField;
        
        private string justificacaoField;
        
        private System.DateTime dataEstadoField;
        
        private string nifComunicouField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serie
        {
            get
            {
                return this.serieField;
            }
            set
            {
                this.serieField = value;
                this.RaisePropertyChanged("serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoSerie
        {
            get
            {
                return this.tipoSerieField;
            }
            set
            {
                this.tipoSerieField = value;
                this.RaisePropertyChanged("tipoSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string classeDoc
        {
            get
            {
                return this.classeDocField;
            }
            set
            {
                this.classeDocField = value;
                this.RaisePropertyChanged("classeDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoDoc
        {
            get
            {
                return this.tipoDocField;
            }
            set
            {
                this.tipoDocField = value;
                this.RaisePropertyChanged("tipoDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public string numInicialSeq
        {
            get
            {
                return this.numInicialSeqField;
            }
            set
            {
                this.numInicialSeqField = value;
                this.RaisePropertyChanged("numInicialSeq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=5)]
        public string numFinalSeq
        {
            get
            {
                return this.numFinalSeqField;
            }
            set
            {
                this.numFinalSeqField = value;
                this.RaisePropertyChanged("numFinalSeq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
        public System.DateTime dataInicioPrevUtiliz
        {
            get
            {
                return this.dataInicioPrevUtilizField;
            }
            set
            {
                this.dataInicioPrevUtilizField = value;
                this.RaisePropertyChanged("dataInicioPrevUtiliz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=7)]
        public string seqUltimoDocEmitido
        {
            get
            {
                return this.seqUltimoDocEmitidoField;
            }
            set
            {
                this.seqUltimoDocEmitidoField = value;
                this.RaisePropertyChanged("seqUltimoDocEmitido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string meioProcessamento
        {
            get
            {
                return this.meioProcessamentoField;
            }
            set
            {
                this.meioProcessamentoField = value;
                this.RaisePropertyChanged("meioProcessamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=9)]
        public string numCertSWFatur
        {
            get
            {
                return this.numCertSWFaturField;
            }
            set
            {
                this.numCertSWFaturField = value;
                this.RaisePropertyChanged("numCertSWFatur");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string codValidacaoSerie
        {
            get
            {
                return this.codValidacaoSerieField;
            }
            set
            {
                this.codValidacaoSerieField = value;
                this.RaisePropertyChanged("codValidacaoSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=11)]
        public System.DateTime dataRegisto
        {
            get
            {
                return this.dataRegistoField;
            }
            set
            {
                this.dataRegistoField = value;
                this.RaisePropertyChanged("dataRegisto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string motivoEstado
        {
            get
            {
                return this.motivoEstadoField;
            }
            set
            {
                this.motivoEstadoField = value;
                this.RaisePropertyChanged("motivoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string justificacao
        {
            get
            {
                return this.justificacaoField;
            }
            set
            {
                this.justificacaoField = value;
                this.RaisePropertyChanged("justificacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime dataEstado
        {
            get
            {
                return this.dataEstadoField;
            }
            set
            {
                this.dataEstadoField = value;
                this.RaisePropertyChanged("dataEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string nifComunicou
        {
            get
            {
                return this.nifComunicouField;
            }
            set
            {
                this.nifComunicouField = value;
                this.RaisePropertyChanged("nifComunicou");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class consultSeriesResp : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private seriesInfo[] infoSerieField;
        
        private operationResultInfo infoResultOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoSerie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public seriesInfo[] infoSerie
        {
            get
            {
                return this.infoSerieField;
            }
            set
            {
                this.infoSerieField = value;
                this.RaisePropertyChanged("infoSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public operationResultInfo infoResultOper
        {
            get
            {
                return this.infoResultOperField;
            }
            set
            {
                this.infoResultOperField = value;
                this.RaisePropertyChanged("infoResultOper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://at.gov.pt/")]
    public partial class operationResultInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string codResultOperField;
        
        private string msgResultOperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string codResultOper
        {
            get
            {
                return this.codResultOperField;
            }
            set
            {
                this.codResultOperField = value;
                this.RaisePropertyChanged("codResultOper");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msgResultOper
        {
            get
            {
                return this.msgResultOperField;
            }
            set
            {
                this.msgResultOperField = value;
                this.RaisePropertyChanged("msgResultOper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registarSerie", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class registarSerieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoSerie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string classeDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numInicialSeq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime dataInicioPrevUtiliz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string numCertSWFatur;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string meioProcessamento;
        
        public registarSerieRequest()
        {
        }
        
        public registarSerieRequest(string serie, string tipoSerie, string classeDoc, string tipoDoc, string numInicialSeq, System.DateTime dataInicioPrevUtiliz, string numCertSWFatur, string meioProcessamento)
        {
            this.serie = serie;
            this.tipoSerie = tipoSerie;
            this.classeDoc = classeDoc;
            this.tipoDoc = tipoDoc;
            this.numInicialSeq = numInicialSeq;
            this.dataInicioPrevUtiliz = dataInicioPrevUtiliz;
            this.numCertSWFatur = numCertSWFatur;
            this.meioProcessamento = meioProcessamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registarSerieResponse", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class registarSerieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceSeriesWS.seriesResp registarSerieResp;
        
        public registarSerieResponse()
        {
        }
        
        public registarSerieResponse(ServiceSeriesWS.seriesResp registarSerieResp)
        {
            this.registarSerieResp = registarSerieResp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="finalizarSerie", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class finalizarSerieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string classeDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codValidacaoSerie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string seqUltimoDocEmitido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string justificacao;
        
        public finalizarSerieRequest()
        {
        }
        
        public finalizarSerieRequest(string serie, string classeDoc, string tipoDoc, string codValidacaoSerie, string seqUltimoDocEmitido, string justificacao)
        {
            this.serie = serie;
            this.classeDoc = classeDoc;
            this.tipoDoc = tipoDoc;
            this.codValidacaoSerie = codValidacaoSerie;
            this.seqUltimoDocEmitido = seqUltimoDocEmitido;
            this.justificacao = justificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="finalizarSerieResponse", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class finalizarSerieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceSeriesWS.seriesResp finalizarSerieResp;
        
        public finalizarSerieResponse()
        {
        }
        
        public finalizarSerieResponse(ServiceSeriesWS.seriesResp finalizarSerieResp)
        {
            this.finalizarSerieResp = finalizarSerieResp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSeries", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class consultarSeriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoSerie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string classeDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codValidacaoSerie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime dataRegistoDe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime dataRegistoAte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string meioProcessamento;
        
        public consultarSeriesRequest()
        {
        }
        
        public consultarSeriesRequest(string serie, string tipoSerie, string classeDoc, string tipoDoc, string codValidacaoSerie, System.DateTime dataRegistoDe, System.DateTime dataRegistoAte, string estado, string meioProcessamento)
        {
            this.serie = serie;
            this.tipoSerie = tipoSerie;
            this.classeDoc = classeDoc;
            this.tipoDoc = tipoDoc;
            this.codValidacaoSerie = codValidacaoSerie;
            this.dataRegistoDe = dataRegistoDe;
            this.dataRegistoAte = dataRegistoAte;
            this.estado = estado;
            this.meioProcessamento = meioProcessamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSeriesResponse", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class consultarSeriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceSeriesWS.consultSeriesResp consultarSeriesResp;
        
        public consultarSeriesResponse()
        {
        }
        
        public consultarSeriesResponse(ServiceSeriesWS.consultSeriesResp consultarSeriesResp)
        {
            this.consultarSeriesResp = consultarSeriesResp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anularSerie", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class anularSerieRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string classeDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codValidacaoSerie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool declaracaoNaoEmissao;
        
        public anularSerieRequest()
        {
        }
        
        public anularSerieRequest(string serie, string classeDoc, string tipoDoc, string codValidacaoSerie, string motivo, bool declaracaoNaoEmissao)
        {
            this.serie = serie;
            this.classeDoc = classeDoc;
            this.tipoDoc = tipoDoc;
            this.codValidacaoSerie = codValidacaoSerie;
            this.motivo = motivo;
            this.declaracaoNaoEmissao = declaracaoNaoEmissao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anularSerieResponse", WrapperNamespace="http://at.gov.pt/", IsWrapped=true)]
    public partial class anularSerieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://at.gov.pt/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceSeriesWS.seriesResp anularSerieResp;
        
        public anularSerieResponse()
        {
        }
        
        public anularSerieResponse(ServiceSeriesWS.seriesResp anularSerieResp)
        {
            this.anularSerieResp = anularSerieResp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface SeriesWSChannel : ServiceSeriesWS.SeriesWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SeriesWSClient : System.ServiceModel.ClientBase<ServiceSeriesWS.SeriesWS>, ServiceSeriesWS.SeriesWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SeriesWSClient() : 
                base(SeriesWSClient.GetDefaultBinding(), SeriesWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SeriesWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesWSClient(EndpointConfiguration endpointConfiguration) : 
                base(SeriesWSClient.GetBindingForEndpoint(endpointConfiguration), SeriesWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SeriesWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SeriesWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceSeriesWS.registarSerieResponse> registarSerieAsync(ServiceSeriesWS.registarSerieRequest request)
        {
            return base.Channel.registarSerieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSeriesWS.finalizarSerieResponse> finalizarSerieAsync(ServiceSeriesWS.finalizarSerieRequest request)
        {
            return base.Channel.finalizarSerieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSeriesWS.consultarSeriesResponse> consultarSeriesAsync(ServiceSeriesWS.consultarSeriesRequest request)
        {
            return base.Channel.consultarSeriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSeriesWS.anularSerieResponse> anularSerieAsync(ServiceSeriesWS.anularSerieRequest request)
        {
            return base.Channel.anularSerieAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SeriesWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SeriesWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://servicos.portaldasfinancas.gov.pt:722/SeriesWSService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SeriesWSClient.GetBindingForEndpoint(EndpointConfiguration.SeriesWSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SeriesWSClient.GetEndpointAddress(EndpointConfiguration.SeriesWSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            SeriesWSPort,
        }
    }
}
