//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTransportDocumentsWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", ConfigurationName="ServiceTransportDocumentsWS.documentosTransporte")]
    public interface documentosTransporte
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceTransportDocumentsWS.envioDocumentoTransporteResponse> envioDocumentoTransporteAsync(ServiceTransportDocumentsWS.envioDocumentoTransporteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class StockMovement
    {
        
        private string taxRegistrationNumberField;
        
        private string companyNameField;
        
        private AddressStructurePT companyAddressField;
        
        private string documentNumberField;
        
        private string aTCUDField;
        
        private string aTDocCodeIDField;
        
        private MovementStatus movementStatusField;
        
        private System.DateTime movementDateField;
        
        private MovementType movementTypeField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private AddressStructurePT customerAddressField;
        
        private string customerNameField;
        
        private AddressStructurePT addressToField;
        
        private AddressStructurePT addressFromField;
        
        private System.DateTime movementEndTimeField;
        
        private bool movementEndTimeFieldSpecified;
        
        private System.DateTime movementStartTimeField;
        
        private string vehicleIDField;
        
        private Line[] lineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string TaxRegistrationNumber
        {
            get
            {
                return this.taxRegistrationNumberField;
            }
            set
            {
                this.taxRegistrationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public AddressStructurePT CompanyAddress
        {
            get
            {
                return this.companyAddressField;
            }
            set
            {
                this.companyAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ATCUD
        {
            get
            {
                return this.aTCUDField;
            }
            set
            {
                this.aTCUDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ATDocCodeID
        {
            get
            {
                return this.aTDocCodeIDField;
            }
            set
            {
                this.aTDocCodeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public MovementStatus MovementStatus
        {
            get
            {
                return this.movementStatusField;
            }
            set
            {
                this.movementStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=7)]
        public System.DateTime MovementDate
        {
            get
            {
                return this.movementDateField;
            }
            set
            {
                this.movementDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public MovementType MovementType
        {
            get
            {
                return this.movementTypeField;
            }
            set
            {
                this.movementTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerTaxID", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlElementAttribute("SupplierTaxID", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public AddressStructurePT CustomerAddress
        {
            get
            {
                return this.customerAddressField;
            }
            set
            {
                this.customerAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public AddressStructurePT AddressTo
        {
            get
            {
                return this.addressToField;
            }
            set
            {
                this.addressToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public AddressStructurePT AddressFrom
        {
            get
            {
                return this.addressFromField;
            }
            set
            {
                this.addressFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime MovementEndTime
        {
            get
            {
                return this.movementEndTimeField;
            }
            set
            {
                this.movementEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MovementEndTimeSpecified
        {
            get
            {
                return this.movementEndTimeFieldSpecified;
            }
            set
            {
                this.movementEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public System.DateTime MovementStartTime
        {
            get
            {
                return this.movementStartTimeField;
            }
            set
            {
                this.movementStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string VehicleID
        {
            get
            {
                return this.vehicleIDField;
            }
            set
            {
                this.vehicleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public Line[] Line
        {
            get
            {
                return this.lineField;
            }
            set
            {
                this.lineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class AddressStructurePT
    {
        
        private string addressdetailField;
        
        private string cityField;
        
        private string postalCodeField;
        
        private string countryField;
        
        public AddressStructurePT()
        {
            this.countryField = "PT";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Addressdetail
        {
            get
            {
                return this.addressdetailField;
            }
            set
            {
                this.addressdetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class ResponseStatus
    {
        
        private string returnCodeField;
        
        private string returnMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string ReturnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class StockMovementResponse
    {
        
        private ResponseStatus[] responseStatusField;
        
        private string documentNumberField;
        
        private string aTCUDField;
        
        private string aTDocCodeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ResponseStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseStatus[] ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ATCUD
        {
            get
            {
                return this.aTCUDField;
            }
            set
            {
                this.aTCUDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ATDocCodeID
        {
            get
            {
                return this.aTDocCodeIDField;
            }
            set
            {
                this.aTDocCodeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class OrderReferences
    {
        
        private string originatingONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OriginatingON
        {
            get
            {
                return this.originatingONField;
            }
            set
            {
                this.originatingONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public partial class Line
    {
        
        private OrderReferences[] orderReferencesField;
        
        private string productDescriptionField;
        
        private decimal quantityField;
        
        private string unitOfMeasureField;
        
        private decimal unitPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderReferences", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OrderReferences[] OrderReferences
        {
            get
            {
                return this.orderReferencesField;
            }
            set
            {
                this.orderReferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ProductDescription
        {
            get
            {
                return this.productDescriptionField;
            }
            set
            {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UnitOfMeasure
        {
            get
            {
                return this.unitOfMeasureField;
            }
            set
            {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal UnitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public enum MovementStatus
    {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/")]
    public enum MovementType
    {
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GC,
        
        /// <remarks/>
        GD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":CustomerTaxID")]
        CustomerTaxID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":SupplierTaxID")]
        SupplierTaxID,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class envioDocumentoTransporteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", Order=0)]
        public ServiceTransportDocumentsWS.StockMovement envioDocumentoTransporteRequestElem;
        
        public envioDocumentoTransporteRequest()
        {
        }
        
        public envioDocumentoTransporteRequest(ServiceTransportDocumentsWS.StockMovement envioDocumentoTransporteRequestElem)
        {
            this.envioDocumentoTransporteRequestElem = envioDocumentoTransporteRequestElem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class envioDocumentoTransporteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/", Order=0)]
        public ServiceTransportDocumentsWS.StockMovementResponse envioDocumentoTransporteResponseElem;
        
        public envioDocumentoTransporteResponse()
        {
        }
        
        public envioDocumentoTransporteResponse(ServiceTransportDocumentsWS.StockMovementResponse envioDocumentoTransporteResponseElem)
        {
            this.envioDocumentoTransporteResponseElem = envioDocumentoTransporteResponseElem;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface documentosTransporteChannel : ServiceTransportDocumentsWS.documentosTransporte, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class documentosTransporteClient : System.ServiceModel.ClientBase<ServiceTransportDocumentsWS.documentosTransporte>, ServiceTransportDocumentsWS.documentosTransporte
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public documentosTransporteClient() : 
                base(documentosTransporteClient.GetDefaultBinding(), documentosTransporteClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.documentosTransporteSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public documentosTransporteClient(EndpointConfiguration endpointConfiguration) : 
                base(documentosTransporteClient.GetBindingForEndpoint(endpointConfiguration), documentosTransporteClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public documentosTransporteClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(documentosTransporteClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public documentosTransporteClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(documentosTransporteClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public documentosTransporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTransportDocumentsWS.envioDocumentoTransporteResponse> ServiceTransportDocumentsWS.documentosTransporte.envioDocumentoTransporteAsync(ServiceTransportDocumentsWS.envioDocumentoTransporteRequest request)
        {
            return base.Channel.envioDocumentoTransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTransportDocumentsWS.envioDocumentoTransporteResponse> envioDocumentoTransporteAsync(ServiceTransportDocumentsWS.StockMovement envioDocumentoTransporteRequestElem)
        {
            ServiceTransportDocumentsWS.envioDocumentoTransporteRequest inValue = new ServiceTransportDocumentsWS.envioDocumentoTransporteRequest();
            inValue.envioDocumentoTransporteRequestElem = envioDocumentoTransporteRequestElem;
            return ((ServiceTransportDocumentsWS.documentosTransporte)(this)).envioDocumentoTransporteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.documentosTransporteSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.documentosTransporteSOAP))
            {
                return new System.ServiceModel.EndpointAddress("https://servicos.portaldasfinancas.gov.pt/sgdtws/documentosTransporte/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return documentosTransporteClient.GetBindingForEndpoint(EndpointConfiguration.documentosTransporteSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return documentosTransporteClient.GetEndpointAddress(EndpointConfiguration.documentosTransporteSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            documentosTransporteSOAP,
        }
    }
}
